#pragma once

#define MASTER_LEFT

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 250

#define MOUSEKEY_WHEEL_INIIAL_MOVEMENTS 0
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 128
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 1

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 8
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 112
#define MOUSEKEY_TIME_TO_MAX 50
#define MOUSEKEY_FRICTION 20
#define MOUSEKEY_MOVE_DELTA 1

#define OLED_FONT_H "lib/glcdfont_lily.c"
#define OLED_FONT_START 0
#define OLED_FONT_END 223
#define OLED_FONT_WIDTH 6
#define OLED_FONT_HEIGHT 8
#define OLED_TIMEOUT 15000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 0

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define IGNORE_MOD_TAP_INTERRUPT

#undef RGBLED_NUM
